// lib/manualsData.ts

export type ManualPhoto = {
  file: string;   // public/manuals/<folder>/ 아래 실제 파일명
  label: string;  // 화면에 표시할 기종명
};

export type Manufacturer = {
  key: string;      // 폴더명 (영문)
  label: string;    // 화면에 표시할 제조사명
  photos: ManualPhoto[];
};

export const MANUALS_DATA: Manufacturer[] = [
  {
    key: 'hyundai',
    label: '현대엘리베이터',
    photos: [
      { file: '60vf.png', label: '60VF' },
      { file: 'baxvf.png', label: 'BAXVF' },
      { file: 'fi-4.png', label: 'FI-4' },
      { file: 'fivf-2.png', label: 'FIVF-2' },
      { file: 'lxvf1.png', label: 'LXVF1' },
      { file: 'ssvf-1.png', label: 'SSVF-1' },
      { file: 'ssvf-5.png', label: 'SSVF-5' },
      { file: 'ssvf-7.png', label: 'SSVF-7' },
      { file: 'stvf-1.png', label: 'STVF-1' },
      { file: 'stvf-2.png', label: 'STVF-2' },
      { file: 'stvf-3.png', label: 'STVF-3' },
      { file: 'stvf-4.png', label: 'STVF-4' },
      { file: 'stvf-5.png', label: 'STVF-5' },
      { file: 'stvf-7.png', label: 'STVF-7' },
      { file: 't&s.png', label: 'T&S' },
      { file: 't3.png', label: 'T3' },
      { file: 'vac.png', label: 'VAC' },
      { file: 'vvsr.png', label: 'VVSR' },
      { file: 'wcvf.png', label: 'WCVF' },
    ],
  },
  {
    key: 'otis',
    label: '오티스',
    photos: [
      { file: 'ac-sl.png', label: 'AC-SL' },
      { file: 'ac2.png', label: 'AC2' },
      { file: 'acd3.png', label: 'ACD3' },
      { file: 'acm.png', label: 'ACM' },
      { file: 'di1.png', label: 'DI1' },
      { file: 'di2.png', label: 'DI2' },
      { file: 'dp.png', label: 'DP' },
      { file: 'ds-4.png', label: 'DS-4' },
      { file: 'e1lp.png', label: 'E1LP' },
      { file: 'e4lp.png', label: 'E4LP' },
      { file: 'f2.png', label: 'F2' },
      { file: 'fec.png', label: 'FEC' },
      { file: 'gen2.png', label: 'GEN2' },
      { file: 'hmi.png', label: 'HMI' },
      { file: 'lei.png', label: 'LEI' },
      { file: 'lgp.png', label: 'LGP' },
      { file: 'lvp.png', label: 'LVP' },
      { file: 'mei.png', label: 'MEI' },
      { file: 'mgp.png', label: 'MGP' },
      { file: 'mvp.png', label: 'MVP' },
      { file: 'nv1.png', label: 'NV1' },
      { file: 'sa-1.png', label: 'SA-1' },
      { file: 'si1.png', label: 'SI1' },
      { file: 'sv-gd.png', label: 'SV-GD' },
      { file: 'toec40.png', label: 'TOEC40' },
      { file: 'vpl.png', label: 'VPL' },
      { file: 'vpl2.png', label: 'VPL2' },
      { file: 'vpl3.png', label: 'VPL3' },
      { file: 'vpl4.png', label: 'VPL4' },
    ],
  },
  {
    key: 'schindler',
    label: '쉰들러엘리베이터',
    photos: [
      { file: 'MRL기종.png', label: 'MRL기종' },
      { file: 'PLC기종(VVVF).png', label: 'PLC기종(VVVF)' },
      { file: '삼일기종(SICON).png', label: '삼일기종(SICON)' },
      { file: '소보기종.png', label: '소보기종' },
    ],
  },
  {
    key: 'kone',
    label: '코네',
    photos: [
      { file: 'MONOSPACE.png', label: 'MONOSPACE' },
    ],
  },
  {
    key: 'mitsubishi',
    label: '미쓰비시',
    photos: [
      { file: 'ELENESSA.png', label: 'ELENESSA' },
      { file: 'GPM.png', label: 'GPM' },
      { file: 'GPS.png', label: 'GPS' },
      { file: 'NEXPIA.png', label: 'NEXPIA' },
      { file: 'NEXWAY.png', label: 'NEXWAY' },
      { file: 'NOBLE.png', label: 'NOBLE' },
    ],
  },
  {
    key: 'toshiba',
    label: '도시바',
    photos: [
      { file: 'CL-200(Gear less).png', label: 'CL-200(Gear less)' },
    ],
  },
  {
    key: 'fujitec',
    label: '후지테크',
    photos: [
      { file: 'AC-2.png', label: 'AC-2' },
      { file: 'AC-GL.png', label: 'AC-GL' },
      { file: 'DC-GL.png', label: 'DC-GL' },
      { file: 'EXDNⅱ.png', label: 'EXDNⅡ' },
      { file: 'FSDN.png', label: 'FSDN' },
      { file: 'RSDN.png', label: 'RSDN' },
      { file: 'XivF.png', label: 'XivF' },
      { file: 'XivF3.png', label: 'XivF3' },
    ],
  },
  {
    key: 'tke',
    label: 'TKE',
    photos: [
      { file: 'dy20.png', label: 'DY20' },
      { file: 'dy20b.png', label: 'DY20B' },
      { file: 'dy30.png', label: 'DY30' },
      { file: 'dy40l.png', label: 'DY40L' },
      { file: 'evolution2.png', label: 'EVOLUTION2' },
      { file: 'tk-ev1.png', label: 'TK-EV1' },
      { file: 'tk-gl1.png', label: 'TK-GL1' },
      { file: 'tk50g.png', label: 'TK50G' },
      { file: 'tk50m.png', label: 'TK50M' },
    ],
  },
  {
    key: 'others',
    label: '그외승강기',
    photos: [
      { file: 'AC-1.png', label: 'AC-1' },
      { file: 'DSF-100.png', label: 'DSF-100' },
      { file: 'VVVF삼일인버터의 기판타입.png', label: 'VVVF삼일인버터의 기판타입' },
      { file: 'VVVF삼일인버터의 기판타입3001.png', label: 'VVVF삼일인버터의 기판타입3001' },
      { file: '대덕 로프식.png', label: '대덕 로프식' },
      { file: '대명 vvvf 2001.png', label: '대명 VVVF 2001' },
      { file: '대명 vvvf 3001.png', label: '대명 VVVF 3001' },
      { file: '대명 유압식.png', label: '대명 유압식' },
      { file: '대진 덤웨이터.png', label: '대진 덤웨이터' },
      { file: '동남 로프식.png', label: '동남 로프식' },
      { file: '동아 vvvf.png', label: '동아 VVVF' },
      { file: '동호 로프식.png', label: '동호 로프식' },
      { file: '명원 덤웨이터.png', label: '명원 덤웨이터' },
      { file: '미주 덤웨이터.png', label: '미주 덤웨이터' },
      { file: '삼일 2001.png', label: '삼일 2001' },
      { file: '삼일 4000.png', label: '삼일 4000' },
      { file: '세계 유압식.png', label: '세계 유압식' },
      { file: '세명 유압식.png', label: '세명 유압식' },
      { file: '송산 PLC-MRL.png', label: '송산 PLC-MRL' },
      { file: '승우 EV-100.png', label: '승우 EV-100' },
      { file: '신동양 덤웨이터.png', label: '신동양 덤웨이터' },
      { file: '신원기전 EN-MRL.png', label: '신원기전 EN-MRL' },
      { file: '신한 VVVF.png', label: '신한 VVVF' },
      { file: '우성 로프식.png', label: '우성 로프식' },
      { file: '우신 로프식.png', label: '우신 로프식' },
      { file: '유일 EV-100.png', label: '유일 EV-100' },
      { file: '유일 VVAC.png', label: '유일 VVAC' },
      { file: '일흥 로프식.png', label: '일흥 로프식' },
      { file: '제일 VVVF.png', label: '제일 VVVF' },
      { file: '중앙 PLC.png', label: '중앙 PLC' },
      { file: '진흥 VVVF.png', label: '진흥 VVVF' },
      { file: '진흥 덤웨이터.png', label: '진흥 덤웨이터' },
      { file: '태산 VVAC.png', label: '태산 VVAC' },
      { file: '태산 덤웨이터.png', label: '태산 덤웨이터' },
      { file: '하나로 덤웨이터.png', label: '하나로 덤웨이터' },
      { file: '한국승강기 제작소 유압식.png', label: '한국승강기 제작소 유압식' },
      { file: '한국엘리베이터 LOGIC-V.png', label: '한국엘리베이터 LOGIC-V' },
      { file: '한국엘리베이터 VVAC.png', label: '한국엘리베이터 VVAC' },
      { file: '한국엘리베이터 VVVF.png', label: '한국엘리베이터 VVVF' },
      { file: '한국테크 VVAC.png', label: '한국테크 VVAC' },
      { file: '한독 VVVF.png', label: '한독 VVVF' },
      { file: '한림 EV-100.png', label: '한림 EV-100' },
      { file: '한림 PLC타입 승객용.png', label: '한림 PLC타입 승객용' },
      { file: '한림 PLC타입 화물용.png', label: '한림 PLC타입 화물용' },
      { file: '한양공업 ATI40.png', label: '한양공업 ATI40' },
      { file: '한영공영 ISO-16M.png', label: '한영공영 ISO-16M' },
      { file: '한진 로프식.png', label: '한진 로프식' },
    ],
  },
];
